In [1]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.personality_traits.compassion_scale import compassion_scale_questionnaire

/home/amonfadi/.local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:481: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(

In [2]:
# Import CS questions
cs_qmnli_df = compassion_scale_questionnaire['QMNLI']
cs_questions = cs_qmnli_df.get_questions()



cs_factors = list(set([q()._descriptor['Factor'] for q in cs_questions]))


# Define CS factors
# cs_factors = [
#     "Kindness",
#     "Common Humanity",
#     "Mindfulness",
#     "Indifference",
#     "Separation",
#     "Disengagement"
# ]

In [3]:
# # Create validator instance
# validator = QuestionnaireValidator(
#     questionnaire_name="CS",
#     questions=cs_questions,
#     factors=cs_factors,
#     result_path="results/",
#     update=False
# )

### Get Results For a Single Question

In [4]:
# semantic_results = validator.get_semantic_similarity(cs_questions[0]())
# cola_results = validator.get_cola_score(cs_questions[0]())
# semantic_results, cola_results

### Evaluate a Single Question

In [5]:
# question_to_evaluate = cs_questions[0] # first question
# # Create validator instance
# validator = QuestionnaireValidator(
#     questionnaire_name="CS",
#     questions=[question_to_evaluate],
#     factors=cs_factors,
#     result_path="results/",
#     update=True
# )

In [6]:

results = validator.run_validation()

NameError: name 'validator' is not defined

In [ ]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [ ]:
results['results_csv']

PosixPath('results/cs_mnli_results.csv')

In [ ]:
results['content_validity']

                     semantic_similarity  cola_score  silhouette_score
Q
CSMindfulness9                  0.838430    0.849823          0.253900
CSIndifference14                0.649457    0.828846          0.340741
CSDisengagement1                0.816734    0.966075          0.342312
CSSeparation22                  0.879695    0.956959          0.416693
CSIndifference12                0.411259    0.912104          0.428294
CSSeparation10                  0.889971    0.888272          0.448230
CSCommon Humanity11             0.767521    0.898494          0.488031
CSIndifference2                 0.852762   -4.444444          0.488767
CSDisengagement7                0.653184    0.970024          0.497373
CSKindness16                    0.602533    0.893874          0.508741
CSDisengagement23               0.790082    0.978627          0.535629
CSCommon Humanity20             0.899775    0.969589          0.570177
CSMindfulness4                  0.847000    0.978119          0.576108
CSKindness8                     0.541537    0.773697          0.587096
CSKindness6                     0.564811    0.903614          0.593198
CSSeparation3                   0.856178    0.957124          0.602966
CSDisengagement19               0.709684    0.973909          0.606718
CSSeparation5                   0.946918    0.909294          0.609201
CSMindfulness21                 0.874526    0.953039          0.610510
CSKindness24                    0.653207    0.924019          0.637772
CSMindfulness13                 0.931448    0.761378          0.649036
CSIndifference18                0.658732    0.951308          0.661812
CSCommon Humanity15             0.821962    0.970311          0.683112
CSCommon Humanity17             0.686275    0.970970          0.697690

In [ ]:
results['cronbach_alpha']["overall"]

(0.9233988461335461, array([0.839, 0.975]))

In [ ]:
results['cronbach_alpha']["factors"]

{'Disengagement': (0.8664445229321031, array([0.665, 0.96 ])),
 'Common Humanity': (0.883693298219234, array([0.708, 0.965])),
 'Mindfulness': (0.7115220643579105, array([0.276, 0.913])),
 'Separation': (0.8394822660993362, array([0.597, 0.952])),
 'Kindness': (0.9286712923060803, array([0.821, 0.978])),
 'Indifference': (0.4342607084822109, array([-0.421,  0.829]))}

In [ ]:
data_df = results['cronbach_alpha']['data_df']
validator.test_question_affect_on_cronbach_alpha(data_df, specific_factors=['Kindness'])

Kindness Alpha: (0.9286712923060803, array([0.821, 0.978]))
without: CSKindness16 Alpha: (0.9714944767806857, array([0.921, 0.992]))
without: CSKindness24 Alpha: (0.8993863658796302, array([0.721, 0.971]))
without: CSKindness6 Alpha: (0.8666467699165195, array([0.63 , 0.961]))
without: CSKindness8 Alpha: (0.8666367536032616, array([0.63 , 0.961]))

In [ ]:
data_df

Q,CSCommon Humanity11,CSCommon Humanity15,CSCommon Humanity17,CSCommon Humanity20,CSDisengagement1,CSDisengagement19,CSDisengagement23,CSDisengagement7,CSIndifference12,CSIndifference14,...,CSKindness6,CSKindness8,CSMindfulness13,CSMindfulness21,CSMindfulness4,CSMindfulness9,CSSeparation10,CSSeparation22,CSSeparation3,CSSeparation5
model,,,,,,,,,,,,,,,,,,,,,
Narsil/deberta-large-mnli-zero-cls,0.030071,0.071995,0.078060,0.035680,0.007929,0.014338,0.018115,0.015700,0.044705,0.065681,...,0.083942,0.081510,0.063152,0.050293,0.063118,0.042474,0.081483,0.101515,0.035494,0.101259
cross-encoder/nli-MiniLM2-L6-H768,0.057885,0.065096,0.065243,0.050079,0.057108,0.016218,0.047265,0.058561,0.019081,0.025546,...,0.054330,0.047081,0.053287,0.031459,0.040160,0.046837,0.093654,0.128763,0.123809,0.055802
cross-encoder/nli-deberta-base,0.065087,0.077900,0.074281,0.052726,0.039844,0.042052,0.028367,0.061726,0.033522,0.031002,...,0.077636,0.076146,0.049050,0.038678,0.037900,0.043783,0.121803,0.119583,0.112517,0.116179
digitalepidemiologylab/covid-twitter-bert-v2-mnli,0.062018,0.058788,0.078296,0.050901,-0.014296,0.023190,0.030217,-0.013344,0.057273,-0.008810,...,0.080042,0.057771,0.072111,0.046322,0.067645,0.046021,0.088564,0.125419,-0.004869,0.087402
joeddav/bart-large-mnli-yahoo-answers,0.008295,0.014450,0.015103,0.003930,-0.002338,0.011231,-0.000096,0.003795,-0.000738,-0.001173,...,0.025344,0.026315,0.025012,0.010308,0.008933,0.010720,0.006113,0.006591,0.006152,0.030862
microsoft/deberta-base-mnli,0.012361,0.073699,0.073939,0.036110,0.055728,0.019291,0.046230,0.073161,0.030104,0.039943,...,0.092614,0.084013,0.067720,0.045512,0.050252,0.027581,0.157336,0.158261,0.058583,0.158952
microsoft/deberta-large-mnli,0.030071,0.071995,0.078060,0.035680,0.007929,0.014338,0.018115,0.015700,0.044705,0.065681,...,0.083942,0.081510,0.063152,0.050293,0.063118,0.042474,0.081483,0.101515,0.035494,0.101259
navteca/bart-large-mnli,0.043513,0.074674,0.082026,0.039156,0.005940,0.061748,0.036957,0.052043,0.018426,0.012320,...,0.099218,0.097514,0.077620,0.050363,0.007123,0.028248,0.138846,0.146322,0.152090,0.168685
typeform/distilbert-base-uncased-mnli,0.063071,0.086961,0.071782,0.052295,0.081472,0.067785,0.089825,0.087475,0.030962,0.032872,...,0.042490,0.055197,0.065664,0.029688,0.068475,0.043434,0.155539,0.122632,0.174462,0.118264
typeform/mobilebert-uncased-mnli,0.065015,0.074768,0.060298,0.042086,0.046891,-0.000307,0.061923,0.050281,0.050051,0.000705,...,0.085505,0.085614,0.053527,0.025134,0.047340,0.005009,0.124983,0.141621,0.124329,0.061937
valhalla/distilbart-mnli-12-6,0.061487,0.076169,0.075674,0.037537,0.008704,0.020253,0.044601,0.028450,0.048093,0.030168,...,0.088780,0.087052,0.050260,0.062305,0.012930,0.013713,0.117013,0.081574,0.096824,0.139522

In [ ]:
results['correlations']

,Disengagement,Common Humanity,Mindfulness,Separation,Kindness,Indifference,CS
Disengagement,-,,,**,,,**
Common Humanity,0.379,-,,,,,
Mindfulness,-0.014,0.059,-,,,,
Separation,0.799,0.434,-0.16,-,,,***
Kindness,0.123,-0.041,-0.16,0.489,-,,
Indifference,0.233,0.032,0.151,0.361,0.562,-,
CS,0.845,0.479,-0.123,0.991,0.406,0.352,-