In [1]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.personality_traits.big5 import big5_questionnaire

/home/amonfadi/.local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:481: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(

In [2]:
# Import big5 questions
big5_qmnli_df = big5_questionnaire['QMNLI']
big5_questions = big5_qmnli_df.get_questions()

big5_factors = list(set([q()._descriptor['Factor'] for q in big5_questions]))

In [ ]:
# Create validator instance
validator = QuestionnaireValidator(
    questionnaire_name="big5",
    questions=big5_questions,
    factors=big5_factors,
    result_path="results/",
)

results = validator.run_validation()

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/utils/generic.py:338: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

Models loaded successfully.
Splitting 14 questions...
Generated 112 question variants.
Initialized big5 Validator:
  - Questions: 14
  - Factors: ['Conscientiousness', 'Extraversion', 'Neuroticism', 'Agreeableness', 'Openness to Experience']
  - Scales: ['frequency']
  - Index: ['index']
  - Device: 0
  - Result path: results

======================================================================
Running Complete Validation for big5 Questionnaire
======================================================================

Running model evaluation with 112 question variants...

Evaluating models:   0%|          | 0/17 [00:00<?, ?it/s]The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

Evaluating model: typeform/distilbert-base-uncased-mnli

The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

Number of labels is 1. Valid values are 2 to n_samples - 1 (inclusive)
silhouette_score is set to -1

In [ ]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [ ]:
results['results_csv']

PosixPath('results/big5_mnli_results.csv')

In [ ]:
results['content_validity']

                             semantic_similarity  cola_score  silhouette_score
Q
BIG5Extraversion7                       0.548206    0.926894          0.294768
BIG5Extraversion8                       0.428702    0.886326          0.374314
BIG5Neuroticism13                       0.620022    0.771979          0.465877
BIG5Neuroticism14                       0.603748    0.844917          0.550385
BIG5Conscientiousness6                  0.443320    0.849632          0.561579
BIG5Openness to Experience2             0.543395    0.863622          0.692454
BIG5Agreeableness10                     0.707367    0.893867          0.697541
BIG5Extraversion9                       0.530604    0.872535          0.748734
BIG5Conscientiousness5                  0.604115    0.708269          0.749364
BIG5Openness to Experience3             0.584912    0.918122          0.792792
BIG5Agreeableness12                     0.642591    0.903656          0.807824
BIG5Agreeableness11                     0.669552    0.922331          0.843528
BIG5Conscientiousness4                  0.593179    0.804102          0.865889
BIG5Openness to Experience1             0.748091    0.729466          0.866986

In [ ]:
results['cronbach_alpha']

{'data_df': Q                                                  BIG5Agreeableness10  \
 model
 Narsil/deberta-large-mnli-zero-cls                            0.067977
 cross-encoder/nli-MiniLM2-L6-H768                             0.077058
 cross-encoder/nli-deberta-base                                0.087334
 digitalepidemiologylab/covid-twitter-bert-v2-mnli             0.073629
 joeddav/bart-large-mnli-yahoo-answers                         0.016478
 microsoft/deberta-base-mnli                                   0.094307
 microsoft/deberta-large-mnli                                  0.067977
 navteca/bart-large-mnli                                       0.110034
 typeform/distilbert-base-uncased-mnli                         0.066108
 typeform/mobilebert-uncased-mnli                              0.067151
 valhalla/distilbart-mnli-12-6                                 0.047564

 Q                                                  BIG5Agreeableness11  \
 model
 Narsil/deberta-large-mnli-zero-cls                            0.052632
 cross-encoder/nli-MiniLM2-L6-H768                             0.085239
 cross-encoder/nli-deberta-base                                0.076412
 digitalepidemiologylab/covid-twitter-bert-v2-mnli             0.087859
 joeddav/bart-large-mnli-yahoo-answers                         0.012332
 microsoft/deberta-base-mnli                                   0.087842
 microsoft/deberta-large-mnli                                  0.052632
 navteca/bart-large-mnli                                       0.104547
 typeform/distilbert-base-uncased-mnli                         0.081329
 typeform/mobilebert-uncased-mnli                              0.086078
 valhalla/distilbart-mnli-12-6                                 0.036918

 Q                                                  BIG5Agreeableness12  \
 model
 Narsil/deberta-large-mnli-zero-cls                            0.061915
 cross-encoder/nli-MiniLM2-L6-H768                             0.061896
 cross-encoder/nli-deberta-base                                0.065261
 digitalepidemiologylab/covid-twitter-bert-v2-mnli             0.024391
 joeddav/bart-large-mnli-yahoo-answers                         0.014963
 microsoft/deberta-base-mnli                                   0.062530
 microsoft/deberta-large-mnli                                  0.061915
 navteca/bart-large-mnli                                       0.089040
 typeform/distilbert-base-uncased-mnli                         0.104812
 typeform/mobilebert-uncased-mnli                              0.097479
 valhalla/distilbart-mnli-12-6                                 0.037297

 Q                                                  BIG5Conscientiousness4  \
 model
 Narsil/deberta-large-mnli-zero-cls                               0.075892
 cross-encoder/nli-MiniLM2-L6-H768                                0.077254
 cross-encoder/nli-deberta-base                                   0.070479
 digitalepidemiologylab/covid-twitter-bert-v2-mnli                0.073650
 joeddav/bart-large-mnli-yahoo-answers                            0.018008
 microsoft/deberta-base-mnli                                      0.104240
 microsoft/deberta-large-mnli                                     0.075892
 navteca/bart-large-mnli                                          0.104731
 typeform/distilbert-base-uncased-mnli                            0.099309
 typeform/mobilebert-uncased-mnli                                 0.109371
 valhalla/distilbart-mnli-12-6                                    0.031892

 Q                                                  BIG5Conscientiousness5  \
 model
 Narsil/deberta-large-mnli-zero-cls                               0.077092
 cross-encoder/nli-MiniLM2-L6-H768                                0.081608
 cross-encoder/nli-deberta-base                                   0.076965
 digitalepidemiologylab/covid-twitter-bert-v2-mnli                0.079456
 joeddav/bart-large-mnli-yahoo-answers                            0.020474
 microsoft/deberta-base-mnli                                      0.081802
 microsoft/deberta-large-mnli                                     0.077092
 navteca/bart-large-mnli                                          0.108149
 typeform/distilbert-base-uncased-mnli                            0.081220
 typeform/mobilebert-uncased-mnli                                 0.073261
 valhalla/distilbart-mnli-12-6                                    0.069654

 Q                                                  BIG5Conscientiousness6  \
 model
 Narsil/deberta-large-mnli-zero-cls                               0.074256
 cross-encoder/nli-MiniLM2-L6-H768                                0.084035
 cross-encoder/nli-deberta-base                                   0.058299
 digitalepidemiologylab/covid-twitter-bert-v2-mnli                0.016435
 joeddav/bart-large-mnli-yahoo-answers                            0.009778
 microsoft/deberta-base-mnli                                      0.060242
 microsoft/deberta-large-mnli                                     0.074256
 navteca/bart-large-mnli                                          0.073706
 typeform/distilbert-base-uncased-mnli                            0.155112
 typeform/mobilebert-uncased-mnli                                 0.149906
 valhalla/distilbart-mnli-12-6                                    0.031830

 Q                                                  BIG5Extraversion7  \
 model
 Narsil/deberta-large-mnli-zero-cls                          0.005146
 cross-encoder/nli-MiniLM2-L6-H768                           0.044027
 cross-encoder/nli-deberta-base                              0.064377
 digitalepidemiologylab/covid-twitter-bert-v2-mnli          -0.005706
 joeddav/bart-large-mnli-yahoo-answers                       0.003734
 microsoft/deberta-base-mnli                                 0.015165
 microsoft/deberta-large-mnli                                0.005146
 navteca/bart-large-mnli                                     0.034565
 typeform/distilbert-base-uncased-mnli                       0.041089
 typeform/mobilebert-uncased-mnli                            0.043170
 valhalla/distilbart-mnli-12-6                               0.010551

 Q                                                  BIG5Extraversion8  \
 model
 Narsil/deberta-large-mnli-zero-cls                          0.030950
 cross-encoder/nli-MiniLM2-L6-H768                           0.076052
 cross-encoder/nli-deberta-base                              0.093385
 digitalepidemiologylab/covid-twitter-bert-v2-mnli           0.009079
 joeddav/bart-large-mnli-yahoo-answers                       0.006117
 microsoft/deberta-base-mnli                                 0.043021
 microsoft/deberta-large-mnli                                0.030950
 navteca/bart-large-mnli                                     0.089390
 typeform/distilbert-base-uncased-mnli                       0.118152
 typeform/mobilebert-uncased-mnli                            0.143058
 valhalla/distilbart-mnli-12-6                               0.015393

 Q                                                  BIG5Extraversion9  \
 model
 Narsil/deberta-large-mnli-zero-cls                          0.026193
 cross-encoder/nli-MiniLM2-L6-H768                           0.067423
 cross-encoder/nli-deberta-base                              0.065368
 digitalepidemiologylab/covid-twitter-bert-v2-mnli           0.008718
 joeddav/bart-large-mnli-yahoo-answers                       0.009556
 microsoft/deberta-base-mnli                                 0.038655
 microsoft/deberta-large-mnli                                0.026193
 navteca/bart-large-mnli                                     0.086967
 typeform/distilbert-base-uncased-mnli                       0.093697
 typeform/mobilebert-uncased-mnli                            0.105524
 valhalla/distilbart-mnli-12-6                               0.028336

 Q                                                  BIG5Neuroticism13  \
 model
 Narsil/deberta-large-mnli-zero-cls                         -0.015241
 cross-encoder/nli-MiniLM2-L6-H768                          -0.046393
 cross-encoder/nli-deberta-base                             -0.033130
 digitalepidemiologylab/covid-twitter-bert-v2-mnli           0.013355
 joeddav/bart-large-mnli-yahoo-answers                      -0.005379
 microsoft/deberta-base-mnli                                -0.023064
 microsoft/deberta-large-mnli                               -0.015241
 navteca/bart-large-mnli                                    -0.097114
 typeform/distilbert-base-uncased-mnli                      -0.042789
 typeform/mobilebert-uncased-mnli                           -0.042297
 valhalla/distilbart-mnli-12-6                              -0.017174

 Q                                                  BIG5Neuroticism14  \
 model
 Narsil/deberta-large-mnli-zero-cls                         -0.010533
 cross-encoder/nli-MiniLM2-L6-H768                          -0.048334
 cross-encoder/nli-deberta-base                             -0.043693
 digitalepidemiologylab/covid-twitter-bert-v2-mnli           0.005901
 joeddav/bart-large-mnli-yahoo-answers                      -0.004051
 microsoft/deberta-base-mnli                                -0.026711
 microsoft/deberta-large-mnli                               -0.010533
 navteca/bart-large-mnli                                    -0.104245
 typeform/distilbert-base-uncased-mnli                      -0.044868
 typeform/mobilebert-uncased-mnli                           -0.061337
 valhalla/distilbart-mnli-12-6                              -0.012668

 Q                                                  BIG5Openness to Experience1  \
 model
 Narsil/deberta-large-mnli-zero-cls                                    0.093370
 cross-encoder/nli-MiniLM2-L6-H768                                     0.101428
 cross-encoder/nli-deberta-base                                        0.082355
 digitalepidemiologylab/covid-twitter-bert-v2-mnli                     0.072550
 joeddav/bart-large-mnli-yahoo-answers                                 0.010898
 microsoft/deberta-base-mnli                                           0.092705
 microsoft/deberta-large-mnli                                          0.093370
 navteca/bart-large-mnli                                               0.101019
 typeform/distilbert-base-uncased-mnli                                 0.108191
 typeform/mobilebert-uncased-mnli                                      0.107066
 valhalla/distilbart-mnli-12-6                                         0.046634

 Q                                                  BIG5Openness to Experience2  \
 model
 Narsil/deberta-large-mnli-zero-cls                                    0.038593
 cross-encoder/nli-MiniLM2-L6-H768                                     0.061579
 cross-encoder/nli-deberta-base                                        0.065028
 digitalepidemiologylab/covid-twitter-bert-v2-mnli                     0.061807
 joeddav/bart-large-mnli-yahoo-answers                                 0.005267
 microsoft/deberta-base-mnli                                           0.029330
 microsoft/deberta-large-mnli                                          0.038593
 navteca/bart-large-mnli                                               0.087033
 typeform/distilbert-base-uncased-mnli                                 0.050261
 typeform/mobilebert-uncased-mnli                                      0.108932
 valhalla/distilbart-mnli-12-6                                         0.028436

 Q                                                  BIG5Openness to Experience3
 model
 Narsil/deberta-large-mnli-zero-cls                                    0.081035
 cross-encoder/nli-MiniLM2-L6-H768                                     0.071509
 cross-encoder/nli-deberta-base                                        0.067712
 digitalepidemiologylab/covid-twitter-bert-v2-mnli                     0.046815
 joeddav/bart-large-mnli-yahoo-answers                                 0.007404
 microsoft/deberta-base-mnli                                           0.070289
 microsoft/deberta-large-mnli                                          0.081035
 navteca/bart-large-mnli                                               0.097966
 typeform/distilbert-base-uncased-mnli                                 0.039494
 typeform/mobilebert-uncased-mnli                                      0.067388
 valhalla/distilbart-mnli-12-6                                         0.025873  ,
 'overall': (0.8623992280207388, array([0.704, 0.956])),
 'factors': {'Conscientiousness': (0.7666390620695904, array([0.353, 0.932])),
  'Neuroticism': (0.9849347941567899, array([0.944, 0.996])),
  'Extraversion': (0.9250607360267873, array([0.792, 0.978])),
  'Openness to Experience': (0.8579777592667364, array([0.606, 0.958])),
  'Agreeableness': (0.8635816044849646, array([0.622, 0.96 ]))}}

In [ ]:
results['correlations']

,Conscientiousness,Neuroticism,Extraversion,Openness to Experience,Agreeableness,big5
Conscientiousness,-,**,**,*,***,***
Neuroticism,-0.763,-,***,**,**,***
Extraversion,0.817,-0.872,-,**,**,***
Openness to Experience,0.644,-0.79,0.735,-,*,**
Agreeableness,0.872,-0.799,0.808,0.662,-,***
big5,0.89,-0.863,0.963,0.79,0.909,-