In [10]:
from qpsychometric.questionnaire_validator import QuestionnaireValidator
from qpsychometric.mental_health.generalized_anxiety_disorder import gad_questionnaire

In [11]:
# Import gad questions
gad_qmnli_df = gad_questionnaire['QMNLI']
gad_questions = gad_qmnli_df.get_questions()

gad_factors = list(set([q()._descriptor['Factor'] for q in gad_questions]))

In [ ]:
# Create validator instance
validator = QuestionnaireValidator(
    questionnaire_name="gad",
    questions=gad_questions,
    factors=gad_factors,
    result_path="results/",
    update=False,
)

results = validator.run_validation()

Loading validation models...

/home/amonfadi/.conda/envs/gpu_env4/lib/python3.9/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [ ]:
results.keys()

dict_keys(['results_csv', 'content_validity', 'cronbach_alpha', 'correlations'])

In [ ]:
results['results_csv']

PosixPath('results/gad_mnli_results.csv')

In [ ]:
results['content_validity']

           semantic_similarity  cola_score  silhouette_score
Q
GAD7GAD73             0.625611    0.834006          0.630896
GAD7GAD75             0.620217    0.869899          0.677813
GAD7GAD72             0.461051    0.879951          0.707341
GAD7GAD71             0.656900    0.936055          0.726579
GAD7GAD77             0.523310    0.933155          0.751356
GAD7GAD76             0.611590    0.852854          0.760295
GAD7GAD74             0.734749    0.924410          0.810173

In [ ]:
results['cronbach_alpha']["overall"]

(0.9557867909490871, array([0.9  , 0.986]))

In [ ]:
results['cronbach_alpha']["factors"]

{'GAD7': (0.9557867909490871, array([0.9  , 0.986]))}

In [ ]:
results['correlations']

     GAD7  gad
GAD7    -  ***
gad   1.0    -